version: "3.8"

services:
  mysql:
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: daycare_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: daycare_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: daycare_backend
    restart: always
    ports:
      - "3337:3337"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mysql
      
  frontend:
    build: ./frontend
    container_name: daycare_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: